print script path and exec error if any

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -7,4 +7,10 @@ set -e
 cd "$(dirname $0)"/..
 
 # find the installers and run them iteratively
-find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
+find . -name install.sh | while read installer ; do
+  echo
+  echo ">>> running $installer"
+  if ! sh -c "${installer}" ; then
+    echo ">>> errors while running $installer"
+  fi
+done
